# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uifW1DezEUQrouvUdlu2aKs21Lokx52F

Train a miniGPT language model using JAX AI Stack.

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### Featured examples

</div>

- [Train a miniGPT language model with JAX AI Stack](https://docs.jaxstack.ai/en/latest/JAX_for_LLM_pretraining.html)
- [LoRA/QLoRA finetuning for LLM using Tunix](https://github.com/google/tunix/blob/main/examples/qlora_gemma.ipynb)
- [Parameter-efficient fine-tuning of Gemma with LoRA and QLoRA](https://keras.io/examples/keras_recipes/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora/)
- [Loading Hugging Face Transformers Checkpoints](https://keras.io/keras_hub/guides/hugging_face_keras_integration/)
- [8-bit Integer Quantization in Keras](https://keras.io/guides/int8_quantization_in_keras/)
- [Float8 training and inference with a simple Transformer model](https://keras.io/examples/keras_recipes/float8_training_and_inference_with_transformer/)
- [Pretraining a Transformer from scratch with KerasHub](https://keras.io/keras_hub/guides/transformer_pretraining/)
- [Simple MNIST convnet](https://keras.io/examples/vision/mnist_convnet/)
- [Image classification from scratch using Keras 3](https://keras.io/examples/vision/image_classification_from_scratch/)
- [Image Classification with KerasHub](https://keras.io/keras_hub/guides/classification_with_keras_hub/)
"""



"""# Task
Train a miniGPT language model using JAX AI Stack.

## Setup JAX AI Stack Environment

### Subtask:
Install the required libraries for JAX AI Stack, including JAX, Flax, Optax, and any other dependencies necessary for miniGPT.

**Reasoning**:
Install the required libraries for JAX AI Stack, including JAX, Flax, Optax, Transformers, and Sentencepiece.

**Reasoning**:
The previous code failed because shell commands (`pip install`) were executed directly in a Python cell without the `!` prefix. I will add `!` to each `pip install` command to correctly execute them as shell commands.
"""

get_ipython().system('pip install --upgrade jax jaxlib==0.4.16+cuda12.cudatoolkit118 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html')
get_ipython().system('pip install flax optax transformers datasets sentencepiece')

"""**Reasoning**:
The previous attempt to install `jaxlib` with a specific CUDA version failed because that exact version was not found. To resolve this, I will modify the installation command to let `pip` automatically select a compatible `jaxlib` version for the installed `jax` and the current Colab environment's CUDA version. I will remove the explicit `jaxlib` version constraint and try to install `jax` and `jaxlib` to ensure compatibility. The other dependencies are already satisfied as per the previous output.


"""

get_ipython().system('pip install --upgrade jax jaxlib -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html')
get_ipython().system('pip install flax optax transformers datasets sentencepiece')

"""## Prepare Dataset

### Subtask:
Load and preprocess a suitable text dataset for training the miniGPT model. This will involve tokenization and creating input-target pairs.

**Reasoning**:
The previous code block was intended to install necessary libraries. The next logical step is to import the required libraries and then load the dataset as per the instructions.
"""

from datasets import load_dataset
from transformers import AutoTokenizer

# Load the dataset
dataset = load_dataset('wikitext', 'wikitext-2-raw-v1')
print(dataset)

"""**Reasoning**:
The dataset is loaded. The next step is to load a pre-trained tokenizer, define a tokenization function, and then tokenize the dataset as per instructions 2, 3, and 4 of the subtask.


"""

tokenizer = AutoTokenizer.from_pretrained('gpt2')
tokenizer.pad_token = tokenizer.eos_token # Set pad_token to eos_token
BLOCK_SIZE = 128

def tokenize_function(examples):
    return tokenizer(examples['text'], truncation=True, padding='max_length', max_length=BLOCK_SIZE)

tokenized_datasets = dataset.map(tokenize_function, batched=True, remove_columns=['text'])
print(tokenized_datasets)

"""**Reasoning**:
The dataset has been tokenized. The next step is to define a function to group consecutive blocks of text into sequences of a fixed length (BLOCK_SIZE) to create input-target pairs, as specified in instruction 5. This will prepare the data for language model training by concatenating all texts and then splitting them into chunks of the desired block size.


"""

def group_texts(examples):
    # Concatenate all texts.
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])
    # We drop the small remainder, we could add padding if the model supported it instead of this drop, you can
    # customize this part to your needs.
    total_length = (total_length // BLOCK_SIZE) * BLOCK_SIZE
    # Split by BLOCK_SIZE.
    result = {
        k: [t[i : i + BLOCK_SIZE] for i in range(0, total_length, BLOCK_SIZE)]
        for k, t in concatenated_examples.items()
    }
    result["labels"] = result["input_ids"].copy()
    return result

# Apply the grouping function to the tokenized dataset
lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    batch_size=1000, # Use a larger batch size for mapping to concatenate more texts at once
    num_proc=1,      # Use a single process for simplicity in Colab, can be increased for faster processing
)

print(lm_datasets)

"""## Define miniGPT Model

### Subtask:
Implement the miniGPT model architecture using Flax (from JAX AI Stack). This includes defining the transformer blocks and the overall model structure.

#### Instructions
1. Import the necessary Flax modules: `nn` from `flax.linen`.
2. Define a class for the Transformer Block, including self-attention, layer normalization, and a feed-forward network. You will need `nn.SelfAttention`, `nn.LayerNorm`, and `nn.Dense`.
3. Define the main miniGPT model class. This class should include token and position embeddings (`nn.Embed`), multiple Transformer Blocks, and a final dense layer for output logits.
4. Ensure the model's `__call__` method processes input sequences through embeddings, transformer blocks, and the final output layer.

**Reasoning**:
The next logical step is to import the required `flax.linen` module and define the `TransformerBlock` class as per instruction 2, including the necessary layers and `__call__` method.
"""

import jax
import jax.numpy as jnp
from flax import linen as nn


class TransformerBlock(nn.Module):
    config: type # Configuration object (e.g., to define hidden_size, num_heads)

    @nn.compact
    def __call__(self, inputs, attention_mask):
        # LayerNorm before self-attention
        normed_inputs = nn.LayerNorm()(inputs)

        # Self-attention layer
        # The attention_mask needs to be processed into an attention bias
        # Flax nn.SelfAttention expects an attention_bias argument
        # For decoder-style attention (causal), you would create a causal mask
        # For standard encoder-style attention, the mask indicates valid tokens

        # Assuming attention_mask is 1 for valid tokens and 0 for padded ones
        # Create an attention bias for padding mask
        attention_bias = nn.make_attention_mask(
            attention_mask > 0, attention_mask > 0, dtype=jnp.float32
        )

        attn_output = nn.SelfAttention(
            num_heads=self.config.num_attention_heads,
            qkv_features=self.config.hidden_size,
            name='self_attention',
        )(normed_inputs, attention_mask=attention_bias)

        # Add skip connection and normalize
        attn_output = inputs + attn_output
        normed_attn_output = nn.LayerNorm()(attn_output)

        # Feed-forward network
        ffn_output = nn.Dense(self.config.intermediate_size, name='wi')(normed_attn_output)
        ffn_output = nn.gelu(ffn_output)
        ffn_output = nn.Dense(self.config.hidden_size, name='wo')(ffn_output)

        # Add skip connection
        output = attn_output + ffn_output
        return output

print("TransformerBlock class defined.")

"""**Reasoning**:
The next step is to define the `MiniGPT` class, incorporating the token and position embeddings, multiple `TransformerBlock` instances, and the final output layer, as per instruction 3 and 4. I will also create a dummy configuration class to pass parameters to the model.


"""

class MiniGPTConfig:
    vocab_size: int = 50257  # GPT-2 vocabulary size
    max_position_embeddings: int = BLOCK_SIZE # Max context length
    hidden_size: int = 768    # Embedding dimension
    num_attention_heads: int = 12 # Number of attention heads
    num_hidden_layers: int = 6 # Number of transformer blocks
    intermediate_size: int = 3072 # Size of the feed-forward network


class MiniGPT(nn.Module):
    config: MiniGPTConfig

    @nn.compact
    def __call__(self, input_ids, attention_mask):
        # Token embeddings
        token_embeddings = nn.Embed(
            num_embeddings=self.config.vocab_size,
            features=self.config.hidden_size,
            name='token_embeddings',
        )(input_ids)

        # Position embeddings
        position_ids = jnp.arange(input_ids.shape[-1], dtype=jnp.int32)
        position_embeddings = nn.Embed(
            num_embeddings=self.config.max_position_embeddings,
            features=self.config.hidden_size,
            name='position_embeddings',
        )(position_ids)

        # Combine embeddings
        embeddings = token_embeddings + position_embeddings

        # Transformer blocks
        x = embeddings
        for i in range(self.config.num_hidden_layers):
            x = TransformerBlock(self.config, name=f'transformer_block_{i}')(x, attention_mask)

        # Final LayerNorm
        x = nn.LayerNorm(name='final_norm')(x)

        # Output layer
        logits = nn.Dense(
            features=self.config.vocab_size,
            name='output_logits',
            kernel_init=nn.initializers.normal(stddev=0.02) # Standard for language models
        )(x)

        return logits

print("MiniGPT model class defined.")

"""**Reasoning**:
The next step is to create a dummy input and initialize the `MiniGPT` model to verify its structure and parameter shapes, as per instruction 5 of the subtask.

**Reasoning**:
The previous code failed because `nn.SelfAttention` in Flax expects `attention_bias` as a keyword argument instead of `attention_mask`. I need to correct the keyword argument in the `TransformerBlock` class definition.
"""

import jax
import jax.numpy as jnp
from flax import linen as nn


class TransformerBlock(nn.Module):
    config: type # Configuration object (e.g., to define hidden_size, num_heads)

    @nn.compact
    def __call__(self, inputs, attention_mask):
        # LayerNorm before self-attention
        normed_inputs = nn.LayerNorm()(inputs)

        # Self-attention layer
        # The attention_mask needs to be processed into an attention bias
        # Flax nn.SelfAttention expects an attention_bias argument
        # For decoder-style attention (causal), you would create a causal mask
        # For standard encoder-style attention, the mask indicates valid tokens

        # Assuming attention_mask is 1 for valid tokens and 0 for padded ones
        # Create an attention bias for padding mask
        attention_bias = nn.make_attention_mask(
            attention_mask > 0, attention_mask > 0, dtype=jnp.float32
        )

        attn_output = nn.SelfAttention(
            num_heads=self.config.num_attention_heads,
            qkv_features=self.config.hidden_size,
            name='self_attention',
        )(normed_inputs, attention_bias=attention_bias) # Corrected keyword argument

        # Add skip connection and normalize
        attn_output = inputs + attn_output
        normed_attn_output = nn.LayerNorm()(attn_output)

        # Feed-forward network
        ffn_output = nn.Dense(self.config.intermediate_size, name='wi')(normed_attn_output)
        ffn_output = nn.gelu(ffn_output)
        ffn_output = nn.Dense(self.config.hidden_size, name='wo')(ffn_output)

        # Add skip connection
        output = attn_output + ffn_output
        return output

print("TransformerBlock class defined.")

"""**Reasoning**:
The previous code failed because `jax.tree_map` is deprecated or moved in the installed JAX version. I will correct the import by using `jax.tree_util.tree_map` instead of `jax.tree_map` to properly display the parameter structure.


"""

import jax
import jax.numpy as jnp
from flax import linen as nn
from jax import tree_util # Import tree_util to access tree_map


class TransformerBlock(nn.Module):
    config: type # Configuration object (e.g., to define hidden_size, num_heads)

    @nn.compact
    def __call__(self, inputs, attention_mask):
        # LayerNorm before self-attention
        normed_inputs = nn.LayerNorm()(inputs)

        # Self-attention layer
        # The attention_mask needs to be processed into an attention bias
        # Flax nn.SelfAttention expects an attention_bias argument
        # For decoder-style attention (causal), you would create a causal mask
        # For standard encoder-style attention, the mask indicates valid tokens

        # Assuming attention_mask is 1 for valid tokens and 0 for padded ones
        # Create an attention bias for padding mask
        attention_bias = nn.make_attention_mask(
            attention_mask > 0, attention_mask > 0, dtype=jnp.float32
        )

        attn_output = nn.SelfAttention(
            num_heads=self.config.num_attention_heads,
            qkv_features=self.config.hidden_size,
            name='self_attention',
        )(normed_inputs, mask=attention_bias) # Corrected keyword argument to 'mask'

        # Add skip connection and normalize
        attn_output = inputs + attn_output
        normed_attn_output = nn.LayerNorm()(attn_output)

        # Feed-forward network
        ffn_output = nn.Dense(self.config.intermediate_size, name='wi')(normed_attn_output)
        ffn_output = nn.gelu(ffn_output)
        ffn_output = nn.Dense(self.config.hidden_size, name='wo')(ffn_output)

        # Add skip connection
        output = attn_output + ffn_output
        return output

print("TransformerBlock class defined.")


class MiniGPTConfig:
    vocab_size: int = 50257  # GPT-2 vocabulary size
    max_position_embeddings: int = BLOCK_SIZE # Max context length
    hidden_size: int = 768    # Embedding dimension
    num_attention_heads: int = 12 # Number of attention heads
    num_hidden_layers: int = 6 # Number of transformer blocks
    intermediate_size: int = 3072 # Size of the feed-forward network


class MiniGPT(nn.Module):
    config: MiniGPTConfig

    @nn.compact
    def __call__(self, input_ids, attention_mask):
        # Token embeddings
        token_embeddings = nn.Embed(
            num_embeddings=self.config.vocab_size,
            features=self.config.hidden_size,
            name='token_embeddings',
        )(input_ids)

        # Position embeddings
        position_ids = jnp.arange(input_ids.shape[-1], dtype=jnp.int32)
        position_embeddings = nn.Embed(
            num_embeddings=self.config.max_position_embeddings,
            features=self.config.hidden_size,
            name='position_embeddings',
        )(position_ids)

        # Combine embeddings
        embeddings = token_embeddings + position_embeddings

        # Transformer blocks
        x = embeddings
        for i in range(self.config.num_hidden_layers):
            x = TransformerBlock(self.config, name=f'transformer_block_{i}')(x, attention_mask)

        # Final LayerNorm
        x = nn.LayerNorm(name='final_norm')(x)

        # Output layer
        logits = nn.Dense(
            features=self.config.vocab_size,
            name='output_logits',
            kernel_init=nn.initializers.normal(stddev=0.02) # Standard for language models
        )(x)

        return logits

print("MiniGPT model class defined.")

config = MiniGPTConfig()
model = MiniGPT(config)

dummy_input_ids = jax.random.randint(jax.random.PRNGKey(0), (1, config.max_position_embeddings), 0, config.vocab_size)
dummy_attention_mask = jnp.ones_like(dummy_input_ids)

# Initialize the model
key = jax.random.PRNGKey(1)
params = model.init(key, dummy_input_ids, dummy_attention_mask)

print("Model initialization successful!")
print("Parameters structure:")
print(tree_util.tree_map(lambda x: x.shape, params))

"""## Configure and Initialize Training State

### Subtask:
Set up the optimizer (e.g., Optax), learning rate schedule, and initialize the model parameters and optimizer state.

## Configure and Initialize Training State

### Subtask:
Set up the optimizer (e.g., Optax), learning rate schedule, and initialize the model parameters and optimizer state.

#### Instructions
1. Import the necessary modules from `optax` for defining the optimizer and learning rate schedule. You will need `optax.adamw` and `optax.warmup_cosine_decay_schedule`.
2. Define a learning rate schedule using `optax.warmup_cosine_decay_schedule`. This schedule should include a warmup period, a constant learning rate phase, and a cosine decay to a minimum learning rate.
3. Define the optimizer using `optax.adamw`, passing in the learning rate schedule and any other desired hyperparameters (e.g., `b1`, `b2`, `eps`).
4. Import `train_state.TrainState` from `flax.training`.
5. Create a `TrainState` class that stores the model parameters, optimizer state, and the `apply_fn` (which is the model's `__call__` method).
6. Instantiate the `TrainState` using the initialized model parameters (`params`), the defined optimizer, and the model's `apply_fn`.

**Reasoning**:
The subtask is to configure and initialize the training state. Following the first instruction, I will import the required modules from `optax`.
"""

import optax

print("Optax modules imported.")

"""**Reasoning**:
The next step is to define a learning rate schedule using `optax.warmup_cosine_decay_schedule` as per instruction 2.


"""

learning_rate = 1e-4
warmup_steps = 1000
cooldown_steps = 10000 # Example value, adjust based on total training steps

# Define the learning rate schedule
lr_schedule = optax.warmup_cosine_decay_schedule(
    init_value=0.0,
    peak_value=learning_rate,
    warmup_steps=warmup_steps,
    decay_steps=cooldown_steps,  # This should be your total training steps or a reasonable fraction
    end_value=learning_rate * 0.01  # Minimum learning rate
)

print("Learning rate schedule defined.")

"""**Reasoning**:
The next step is to define the optimizer using `optax.adamw`, passing in the learning rate schedule and other desired hyperparameters as per instruction 3.


"""

optimizer = optax.adamw(learning_rate=lr_schedule, b1=0.9, b2=0.95, eps=1e-8)

print("Optimizer defined.")

"""**Reasoning**:
The next step is to import `TrainState` from `flax.training`, create a custom `TrainState` class to hold the model parameters and optimizer state, and then instantiate it with the initialized model and optimizer, as per instructions 4, 5, and 6.


"""

from flax.training import train_state


class TrainState(train_state.TrainState):
    # A simple TrainState that includes the model's apply_fn
    apply_fn = MiniGPT.apply

# Instantiate the TrainState
state = TrainState.create(
    apply_fn=model.apply,
    params=params['params'],  # We pass only the learnable parameters
    tx=optimizer
)

print("TrainState defined and instantiated.")

"""## Implement Training Loop

### Subtask:
Define the training function, including forward pass, loss calculation, gradient computation, and parameter updates.

#### Instructions
1. Define a training step function that takes the `TrainState`, a batch of data, and a PRNG key as input.
2. Inside this function, use `jax.value_and_grad` to compute the loss and its gradients with respect to the model parameters.
3. For the forward pass, apply the model using `state.apply_fn` (which is `MiniGPT.apply`) with the current parameters (`state.params`), input IDs, and attention mask from the batch.
4. Calculate the loss. Use `optax.softmax_cross_entropy_with_integer_labels` for loss computation, ensuring to mask out padded tokens if necessary.
5. Compute the gradients using `jax.lax.pmean` to average gradients across devices if multiple devices are used.
6. Update the `TrainState` by applying the gradients to the optimizer using `state.apply_gradients`.
7. Return the updated `TrainState` and the computed loss.

```markdown
## Implement Training Loop

### Subtask:
Define the training function, including forward pass, loss calculation, gradient computation, and parameter updates.

#### Instructions
1. Define a training step function that takes the `TrainState`, a batch of data, and a PRNG key as input.
2. Inside this function, use `jax.value_and_grad` to compute the loss and its gradients with respect to the model parameters.
3. For the forward pass, apply the model using `state.apply_fn` (which is `MiniGPT.apply`) with the current parameters (`state.params`), input IDs, and attention mask from the batch.
4. Calculate the loss. Use `optax.softmax_cross_entropy_with_integer_labels` for loss computation, ensuring to mask out padded tokens if necessary.
5. Compute the gradients using `jax.lax.pmean` to average gradients across devices if multiple devices are used.
6. Update the `TrainState` by applying the gradients to the optimizer using `state.apply_gradients`.
7. Return the updated `TrainState` and the computed loss.
```

**Reasoning**:
The subtask is to define the training function, including forward pass, loss calculation, gradient computation, and parameter updates. I will now implement the `train_step` function as outlined in the instructions.
"""

import jax
import jax.numpy as jnp
import optax

@jax.jit
def train_step(state: TrainState, batch: dict, dropout_rng: jax.Array):
    def loss_fn(params):
        labels = batch['labels']
        # Generate a new dropout RNG key for each forward pass
        logits = state.apply_fn({'params': params}, input_ids=batch['input_ids'], attention_mask=batch['attention_mask'], rngs={'dropout': dropout_rng})

        # Calculate loss
        # Ensure labels are integers for optax.softmax_cross_entropy_with_integer_labels
        one_hot_labels = jax.nn.one_hot(labels, num_classes=state.config.vocab_size)
        loss = optax.softmax_cross_entropy(logits=logits, labels=one_hot_labels)

        # Mask out loss for padded tokens if attention_mask is 0
        # The attention_mask in the batch is 1 for valid tokens, 0 for padded
        # Reshape attention_mask to match loss shape (batch_size, sequence_length)
        mask = batch['attention_mask'].reshape(loss.shape)
        loss = loss * mask

        # Average loss over non-padded tokens
        loss = jnp.sum(loss) / jnp.sum(mask)
        return loss

    grad_fn = jax.value_and_grad(loss_fn)
    loss, grads = grad_fn(state.params)

    # Pmean gradients across devices, if applicable
    grads = jax.lax.pmean(grads, axis_name='batch')

    new_state = state.apply_gradients(grads=grads)
    return new_state, loss

print("Training step function defined.")

"""## Train miniGPT Model

### Subtask:
Execute the training loop for a specified number of epochs or steps using the prepared dataset and initialized training state.

#### Instructions
1. Import `tqdm` for a progress bar during training.
2. Set hyperparameters for training, including the number of epochs and the batch size.
3. Create a data loader for the training dataset, making sure to shuffle and batch the data appropriately.
4. Initialize a PRNG key for the training process.
5. Start a loop for the specified number of epochs.
6. Inside the epoch loop, create another loop to iterate through batches from the data loader.
7. For each batch, generate a new dropout PRNG key for the `train_step` function.
8. Call the `train_step` function with the current training state, the batch, and the dropout PRNG key to update the model parameters and compute the loss.
9. Print the training loss periodically to monitor progress.
10. Periodically save the model checkpoint.

**Reasoning**:
The subtask is to implement the training loop. I will start by importing the `tqdm` library for a progress bar, as per instruction 1.
"""

from tqdm.auto import tqdm

print("tqdm imported.")

"""**Reasoning**:
The next step is to set the hyperparameters for training, including the number of epochs and the batch size, as per instruction 2 of the subtask.


"""

num_epochs = 3
batch_size = 16

print(f"Training will run for {num_epochs} epochs with a batch size of {batch_size}.")

"""**Reasoning**:
The next step is to create a data loader for the training dataset, making sure to shuffle and batch the data appropriately, as per instruction 3 of the subtask.


"""

import tensorflow as tf

# Create a TensorFlow dataset from the Hugging Face dataset
train_dataset = lm_datasets['train'].to_tf_dataset(
    columns=['input_ids', 'attention_mask', 'labels'],
    shuffle=True,
    batch_size=batch_size,
    collate_fn=None,
    # Other parameters if needed, e.g., drop_remainder=True
)

print("Data loader for training dataset created.")

"""**Reasoning**:
The next step is to initialize a PRNG key for the training process, as per instruction 4 of the subtask. This key will be used for randomness in JAX operations, including dropout.


"""

key = jax.random.PRNGKey(0)
print("PRNG key initialized.")

"""**Reasoning**:
Now that the PRNG key is initialized, I will proceed to implement the main training loop as per instructions 5 through 9 of the subtask. This involves iterating over epochs and batches, generating dropout keys, calling the `train_step` function, and printing the training loss periodically.


"""

from flax.training import train_state


class TrainState(train_state.TrainState):
    # A simple TrainState that includes the model's apply_fn and config
    config: MiniGPTConfig  # Add the config to the TrainState
    apply_fn = MiniGPT.apply

# Instantiate the TrainState
state = TrainState.create(
    apply_fn=model.apply,
    params=params['params'],  # We pass only the learnable parameters
    tx=optimizer,
    config=config # Pass the config object here
)

print("TrainState defined and instantiated.")

"""**Reasoning**:
The `TrainState` is now correctly instantiated with the `config` object. I will re-execute the training loop to continue with the model training, which was the original intent before the error.


"""

import jax
import jax.numpy as jnp
import optax

@jax.jit(static_argnames=['config']) # Mark 'config' as a static argument
def train_step(state: TrainState, batch: dict, dropout_rng: jax.Array, config: MiniGPTConfig):
    def loss_fn(params):
        labels = batch['labels']
        # Generate a new dropout RNG key for each forward pass
        logits = state.apply_fn({'params': params}, input_ids=batch['input_ids'], attention_mask=batch['attention_mask'], rngs={'dropout': dropout_rng})

        # Calculate loss
        # Ensure labels are integers for optax.softmax_cross_entropy_with_integer_labels
        one_hot_labels = jax.nn.one_hot(labels, num_classes=config.vocab_size) # Use the passed config
        loss = optax.softmax_cross_entropy(logits=logits, labels=one_hot_labels)

        # Mask out loss for padded tokens if attention_mask is 0
        # The attention_mask in the batch is 1 for valid tokens, 0 for padded
        # Reshape attention_mask to match loss shape (batch_size, sequence_length)
        mask = batch['attention_mask'].reshape(loss.shape)
        loss = loss * mask

        # Average loss over non-padded tokens
        loss = jnp.sum(loss) / jnp.sum(mask)
        return loss

    grad_fn = jax.value_and_grad(loss_fn)
    loss, grads = grad_fn(state.params)

    # Pmean gradients across devices, if applicable
    grads = jax.lax.pmean(grads, axis_name='batch')

    new_state = state.apply_gradients(grads=grads)
    return new_state, loss

print("Training step function defined.")

"""**Reasoning**:
The `train_step` function has been updated to accept `config` as a static argument. Now, I will re-execute the training loop, making sure to pass `state.config` to the `train_step` function to resolve the `TypeError` and proceed with training.


"""

from flax.training import train_state


class TrainState(train_state.TrainState):
    # A simple TrainState that includes the model's apply_fn
    apply_fn = MiniGPT.apply

# Instantiate the TrainState
state = TrainState.create(
    apply_fn=model.apply,
    params=params['params'],  # We pass only the learnable parameters
    tx=optimizer
)

print("TrainState defined and instantiated.")

"""**Reasoning**:
The `TrainState` has been redefined to remove the `config` attribute. Now, I will re-execute the training loop, passing the global `config` object explicitly as the static argument to the `train_step` function to resolve the `TypeError` and proceed with training.


"""

import jax
import jax.numpy as jnp
import optax

@jax.jit(static_argnames=['config'])
def train_step(state: TrainState, batch: dict, dropout_rng: jax.Array, config: MiniGPTConfig):
    def loss_fn(params):
        labels = batch['labels']
        logits = state.apply_fn({'params': params}, input_ids=batch['input_ids'], attention_mask=batch['attention_mask'], rngs={'dropout': dropout_rng})
        one_hot_labels = jax.nn.one_hot(labels, num_classes=config.vocab_size)
        loss = optax.softmax_cross_entropy(logits=logits, labels=one_hot_labels)
        mask = batch['attention_mask'].reshape(loss.shape)
        loss = loss * mask
        loss = jnp.sum(loss) / jnp.sum(mask)
        return loss

    grad_fn = jax.value_and_grad(loss_fn)
    loss, grads = grad_fn(state.params)

    # Removed jax.lax.pmean as it's not needed for single device training with jax.jit
    # If multi-device training is desired, jax.pmap should wrap the train_step function.

    new_state = state.apply_gradients(grads=grads)
    return new_state, loss

print("Training step function defined.")

"""**Reasoning**:
The `train_step` function has been redefined to remove `jax.lax.pmean`. Now, I will re-execute the training loop to continue with the model training, which was the original intent before the error.


"""

for epoch in tqdm(range(num_epochs), desc="Epochs"):
    # Shuffle and create batches for the current epoch
    epoch_train_dataset = lm_datasets['train'].shuffle().to_tf_dataset(
        columns=['input_ids', 'attention_mask', 'labels'],
        shuffle=False, # Already shuffled the HF dataset
        batch_size=batch_size,
        collate_fn=None,
        drop_remainder=True # Ensure fixed batch size for pmap compatibility
    )

    # Reset the dropout_rng for each epoch
    key, dropout_rng = jax.random.split(key)

    for batch_idx, batch_tf in enumerate(tqdm(epoch_train_dataset, desc=f"Epoch {epoch+1} Batches")):
        # Convert TensorFlow batch to JAX numpy arrays
        batch = {
            k: jnp.asarray(v) for k, v in batch_tf.items()
        }

        # Generate a new dropout RNG key for each training step
        dropout_rng, new_dropout_rng = jax.random.split(dropout_rng)

        # Perform a single training step
        state, loss = train_step(state, batch, new_dropout_rng, config) # Pass the global config object here

        if batch_idx % 10 == 0: # Print loss every 10 batches
            tqdm.write(f"Epoch {epoch+1}, Batch {batch_idx}, Loss: {loss:.4f}")

print("Training complete.")

"""# Task
The miniGPT language model has been successfully defined and partially trained using the JAX AI Stack. The environment was set up by installing necessary libraries like JAX, Flax, Optax, Transformers, and Sentencepiece. A text dataset (`wikitext-2-raw-v1`) was loaded, tokenized using a GPT-2 tokenizer, and preprocessed into fixed-size input sequences. The miniGPT model architecture, including Transformer Blocks, was implemented using Flax. The training state was configured with an AdamW optimizer and a warmup-cosine-decay learning rate schedule. Finally, a training loop was initiated, performing forward passes, loss calculations using `optax.softmax_cross_entropy`, and parameter updates via `state.apply_gradients`. The model began training and showed a decreasing loss over the initial batches.

## Train miniGPT Model

### Subtask:
Execute the training loop for a specified number of epochs or steps using the prepared dataset and initialized training state, and save model checkpoints periodically.

**Reasoning**:
The subtask requires saving model checkpoints periodically. I will start by importing the `save_checkpoint` function and defining a directory for checkpoints, as per instructions 1 and 2 of the subtask.
"""

from flax.training import checkpoints

checkpoint_dir = './checkpoints'
print(f"Checkpoint directory set to: {checkpoint_dir}")

"""**Reasoning**:
I will now re-execute the training loop, incorporating the checkpoint saving functionality as per instruction 3, and ensure all other instructions (4, 5, 6) are met within the loop.


"""

for epoch in tqdm(range(num_epochs), desc="Epochs"):
    # Shuffle and create batches for the current epoch
    epoch_train_dataset = lm_datasets['train'].shuffle().to_tf_dataset(
        columns=['input_ids', 'attention_mask', 'labels'],
        shuffle=False, # Already shuffled the HF dataset
        batch_size=batch_size,
        collate_fn=None,
        drop_remainder=True # Ensure fixed batch size for pmap compatibility
    )

    # Reset the dropout_rng for each epoch
    key, dropout_rng = jax.random.split(key)

    for batch_idx, batch_tf in enumerate(tqdm(epoch_train_dataset, desc=f"Epoch {epoch+1} Batches")):
        # Convert TensorFlow batch to JAX numpy arrays
        batch = {
            k: jnp.asarray(v) for k, v in batch_tf.items()
        }

        # Generate a new dropout RNG key for each training step
        dropout_rng, new_dropout_rng = jax.random.split(dropout_rng)

        # Perform a single training step
        state, loss = train_step(state, batch, new_dropout_rng, config) # Pass the global config object here

        if batch_idx % 10 == 0: # Print loss every 10 batches
            tqdm.write(f"Epoch {epoch+1}, Batch {batch_idx}, Loss: {loss:.4f}")

    # Save checkpoint after each epoch
    checkpoints.save_checkpoint(ckpt_dir=checkpoint_dir, target=state, step=epoch, overwrite=True, keep=3)
    tqdm.write(f"Saved checkpoint for epoch {epoch} to {checkpoint_dir}")

print("Training complete.")
